package View;

public class MainOperator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainOperator.class.getName());

    /**
     * Creates new form Operator
     */
    public MainOperator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        collectPaymentButton = new javax.swing.JButton();
        printBillButton = new javax.swing.JButton();
        viewBillsButton = new javax.swing.JButton();
        cancelSubscriptionButton = new javax.swing.JButton();
        setTariffButton = new javax.swing.JButton();
        validateReadingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("operator ui");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 70, 130));
        jLabel1.setText("Operator Dashboard");

        collectPaymentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        collectPaymentButton.setText("Collect Payment");
        collectPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectPaymentButtonActionPerformed(evt);
            }
        });

        printBillButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        printBillButton.setText("Print Bill");
        printBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillButtonActionPerformed(evt);
            }
        });

        viewBillsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewBillsButton.setText("View Bills by Region");
        viewBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillsButtonActionPerformed(evt);
            }
        });

        cancelSubscriptionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelSubscriptionButton.setText("Cancel Subscription");
        cancelSubscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSubscriptionButtonActionPerformed(evt);
            }
        });

        setTariffButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setTariffButton.setText("Set Customer Tariff");
        setTariffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTariffButtonActionPerformed(evt);
            }
        });

        validateReadingButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        validateReadingButton.setText("Validate Reading");
        validateReadingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateReadingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(collectPaymentButton)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setTariffButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printBillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewBillsButton)
                                .addGap(18, 18, 18)
                                .addComponent(validateReadingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelSubscriptionButton))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collectPaymentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBillsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validateReadingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setTariffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelSubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void collectPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectPaymentButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
            CollectPaymentFrame f = new CollectPaymentFrame();
    f.setVisible(true);
    }//GEN-LAST:event_collectPaymentButtonActionPerformed

    private void printBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PrintBillFrame f = new PrintBillFrame();
    f.setVisible(true);
    }//GEN-LAST:event_printBillButtonActionPerformed

    private void viewBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillsButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    ViewRegionBillsFrame f = new ViewRegionBillsFrame();
    f.setVisible(true);
    }//GEN-LAST:event_viewBillsButtonActionPerformed

    private void cancelSubscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSubscriptionButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CancelSubscriptionFrame f = new CancelSubscriptionFrame();
    f.setVisible(true);
    }//GEN-LAST:event_cancelSubscriptionButtonActionPerformed

    private void setTariffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTariffButtonActionPerformed
        // TODO add your handling code here:
              this.dispose();
        SetTariffFrame f = new SetTariffFrame();
    f.setVisible(true);
    }//GEN-LAST:event_setTariffButtonActionPerformed

    private void validateReadingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateReadingButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ValidateReadingFrame f = new ValidateReadingFrame();
    f.setVisible(true);
    }//GEN-LAST:event_validateReadingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainOperator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSubscriptionButton;
    private javax.swing.JButton collectPaymentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printBillButton;
    private javax.swing.JButton setTariffButton;
    private javax.swing.JButton validateReadingButton;
    private javax.swing.JButton viewBillsButton;
    // End of variables declaration//GEN-END:variables
}
