package View;

import Controller.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class ValidateReadingFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ValidateReadingFrame.class.getName());

    /**
     * Creates new form ValidateReadingFrame
     */
    public ValidateReadingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        meterCodeTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameTF = new javax.swing.JTextField();
        perviousReadingTF = new javax.swing.JTextField();
        exConsumptionRangerTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NewReadingTF = new javax.swing.JTextField();
        ValidateButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        saveReadingbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validate Reading");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 70, 130));
        jLabel1.setText("Validate Reading");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Enter Meter Code to Vaildate Reading:");

        meterCodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meterCodeTFActionPerformed(evt);
            }
        });

        jLabel3.setText("Meter Code:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer Name:");

        jLabel5.setText("Expected Consumption Range:");

        jLabel6.setText("Previous Reading (kWh):");

        fullNameTF.setEditable(false);
        fullNameTF.setBackground(new java.awt.Color(204, 204, 204));
        fullNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTFActionPerformed(evt);
            }
        });

        perviousReadingTF.setEditable(false);
        perviousReadingTF.setBackground(new java.awt.Color(204, 204, 204));

        exConsumptionRangerTF.setEditable(false);
        exConsumptionRangerTF.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("New Reading (kWh):");

        NewReadingTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewReadingTFActionPerformed(evt);
            }
        });

        ValidateButton.setText("Validate");
        ValidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidateButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        saveReadingbutton.setText("Save Reading");
        saveReadingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveReadingbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveReadingbutton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(meterCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(SearchButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(fullNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(perviousReadingTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(190, 190, 190)
                                .addComponent(ValidateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NewReadingTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exConsumptionRangerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(meterCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(SearchButton))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fullNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(perviousReadingTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NewReadingTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidateButton))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(exConsumptionRangerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(saveReadingbutton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateButtonActionPerformed
        // TODO add your handling code here:
//        
//       try{
        String newReading = NewReadingTF.getText();
        
        if(Validation.isEmpty(newReading)){
            JOptionPane.showMessageDialog(this, "Please Enter New Reading");
            return;  
            }
        
        if(Validation.isNumber(newReading)){
              JOptionPane.showMessageDialog(this, "Please Enter Number Only");
            return;  
            }
        
        if(!Validation.isPositive(Double.parseDouble(newReading))){
            JOptionPane.showMessageDialog(this, "Please Enter Positive Number Only");
            return;
        }
        
        CustomerController cc = new CustomerController();
        String[] data = cc.searchForCustomer(meterCodeTF.getText());
        if (data == null) {
            JOptionPane.showMessageDialog(this, "Meter not found");
            return;
        }
       

        String perviousReading = data[11];
        String CurrentReading =NewReadingTF.getText();
        double expectedConsumptionRange=Double.parseDouble(CurrentReading)-Double.parseDouble(perviousReading);
        exConsumptionRangerTF.setText(expectedConsumptionRange+"");
        
//        exConsumptionRangerTF.setText(expectedconsumtion+"");
//        } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(
//            this,
//            "Invalid number format in meter code",
//            "Input Error",
//            JOptionPane.ERROR_MESSAGE
//        );
//    }
        
    }//GEN-LAST:event_ValidateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                                this.dispose();
            MainOperator f = new MainOperator();
    f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void meterCodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meterCodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meterCodeTFActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
//        try {
        

        String meterCode =meterCodeTF.getText();
       
        if(Validation.isEmpty(meterCode)){
            JOptionPane.showMessageDialog(this, "Please Enter Meter Code");
            return;  
            }
        
        if(Validation.isNumber(meterCode)){
              JOptionPane.showMessageDialog(this, "Please Enter Number Only");
            return;  
            }
        
        if(!Validation.isPositive(Double.parseDouble(meterCode))){
            JOptionPane.showMessageDialog(this, "Please Enter Positive Number Only");
            return;
        }
        
        CustomerController cc = new CustomerController();
        String[] data = cc.searchForCustomer(meterCode);
        
        if (data == null) {
            JOptionPane.showMessageDialog(this, "Meter not found");
            return;
        }
        
         // nationalId|firstName|lastName|phone|region|email|meterCode|status|contract|Reading|previous Reading|tariff|date|bill
        
   
        
        String fullName = data[1] + " " + data[2];
        String perviousReading = data[11];
        
        fullNameTF.setText(fullName);  
        perviousReadingTF.setText(perviousReading);

//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(
//            this,
//            "Invalid number format in meter code",
//            "Input Error",
//            JOptionPane.ERROR_MESSAGE
//        );
//    }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void NewReadingTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewReadingTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewReadingTFActionPerformed

    private void fullNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTFActionPerformed

    private void saveReadingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReadingbuttonActionPerformed
        // TODO add your handling code here:
        String newReading = NewReadingTF.getText();
        CustomerController cc = new CustomerController();
        cc.setNewReading(meterCodeTF.getText(),Double.parseDouble(newReading));
        JOptionPane.showMessageDialog(
            this,
            "New Reading Has Been Added"
        );
            
        
    }//GEN-LAST:event_saveReadingbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ValidateReadingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewReadingTF;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton ValidateButton;
    private javax.swing.JTextField exConsumptionRangerTF;
    private javax.swing.JTextField fullNameTF;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField meterCodeTF;
    private javax.swing.JTextField perviousReadingTF;
    private javax.swing.JButton saveReadingbutton;
    // End of variables declaration//GEN-END:variables
}
