/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.admin;

/**
 *
 * @author youssef
 */
public class adminDashBoardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminDashBoardJFrame
     */
    public adminDashBoardJFrame() {
        initComponents();
    }
    public adminDashBoardJFrame(String x) {
        initComponents();
        AdminDashBoardLable.setText(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminDashBoardLable = new javax.swing.JLabel();
        ViewBillsButton = new javax.swing.JButton();
        ViewTotalCollectionButton = new javax.swing.JButton();
        ViewStatisticsButton = new javax.swing.JButton();
        ManageUsersButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminDashBoardLable.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        AdminDashBoardLable.setText("Admin dashboard");

        ViewBillsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewBillsButton.setText("View bills");
        ViewBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBillsButtonActionPerformed(evt);
            }
        });

        ViewTotalCollectionButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewTotalCollectionButton.setText("View total collection");
        ViewTotalCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTotalCollectionButtonActionPerformed(evt);
            }
        });

        ViewStatisticsButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ViewStatisticsButton.setText("View statistics");
        ViewStatisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStatisticsButtonActionPerformed(evt);
            }
        });

        ManageUsersButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ManageUsersButton.setText("Manage users");
        ManageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUsersButtonActionPerformed(evt);
            }
        });

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(401, 401, 401))
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(AdminDashBoardLable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ViewBillsButton)
                .addGap(35, 35, 35)
                .addComponent(ViewTotalCollectionButton)
                .addGap(35, 35, 35)
                .addComponent(ViewStatisticsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(ManageUsersButton)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(AdminDashBoardLable)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBillsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewTotalCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewStatisticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewTotalCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTotalCollectionButtonActionPerformed
        // TODO add your handling code here:
        ViewTotalCollectionJFrame c=new ViewTotalCollectionJFrame();
            c.setVisible(true);
    }//GEN-LAST:event_ViewTotalCollectionButtonActionPerformed

    private void ViewBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBillsButtonActionPerformed
        // TODO add your handling code here:
        ViewBillsJFrame b=new ViewBillsJFrame();
            b.setVisible(true);
    }//GEN-LAST:event_ViewBillsButtonActionPerformed

    private void ViewStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStatisticsButtonActionPerformed
        // TODO add your handling code here:
        ViewStatisticsJFrame b=new ViewStatisticsJFrame();
            b.setVisible(true);
    }//GEN-LAST:event_ViewStatisticsButtonActionPerformed

    private void ManageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUsersButtonActionPerformed
        // TODO add your handling code here:
        ManageUserJFrame m=new ManageUserJFrame();
            m.setVisible(true);
    }//GEN-LAST:event_ManageUsersButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        AdminLoginJform l=new AdminLoginJform();
            l.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashBoardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new adminDashBoardJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDashBoardLable;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ManageUsersButton;
    private javax.swing.JButton ViewBillsButton;
    private javax.swing.JButton ViewStatisticsButton;
    private javax.swing.JButton ViewTotalCollectionButton;
    // End of variables declaration//GEN-END:variables
}
